vaadin:
  whitelisted-packages: software/xdev,com/vaadin/flow

spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  jpa:
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: test
    password:
  sql:
    init:
      platform: h2
  h2:
    console:
      enabled: true

