vaadin:
  whitelisted-packages: software/xdev,com/vaadin/flow

spring:
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:tesdb
    username: sa
    password:
    driverClassName: org.h2.Driver


